baseURL = "https://naturaoz.org/"
languageCode = "sk-sk"
defaultContentLanguage = "sk"
title = "NATURA, o.z."

[markup.goldmark.renderer]
  unsafe = true
  
[markup.goldmark.parser.attribute]
block = true

[markup.goldmark.parser]
wrapStandAloneImageWithinParagraph = false


[params]
  description = "NATURA - občianske združenie podporujúce výskumné a vzdelávacie aktivity v biomedicínskych vedách"

[menu]
   [[menu.main]]
    name = "Aktivity"
    url = "/aktivity/"
    weight = 1

   [[menu.main]]
    name = "Kuželove semináre"
    url = "/kuzelove-seminare/"
    weight = 2

   [[menu.main]]
    name = "Natura Lectures"
    url = "/natura-lectures/"
    weight = 3

   [[menu.main]]
    name = "Peter Fedor"
    url = "/peter-fedor/"
    weight = 4

   [[menu.main]]
    name = "Galérie"
    url = "/galerie/"
    weight = 5

   [[menu.main]]
    name = "Ocenenia"
    url = "/ocenenia/"
    weight = 6

   [[menu.main]]
    name = "Journal Club"
    url = "/journal-club/"
    weight = 7

   [[menu.main]]
    name = "TalNet Project"
    url = "/talnet-project/"
    weight = 8

   [[menu.main]]
    name = "Fotosúťaž"
    url = "/fotosutaz/"
    weight = 9

   [[menu.main]]
    name = "Podporte nás"
    url = "/podporte-nas/"
    weight = 10
